### ISSUE TITLE
Who To Follow broken

### ISSUE THREAD

**Issue by ludochane** [ippontech/tatami#870]
The "Who To Follow" section seems to be broken.
A new Ippon (@qleuly) just arrived today and the "Who To Follow" section does not propose me to follow @qleuly

**Comment by hegek87** [comment]
This may be an issue with it taking some time to recognize someone as a user to suggest. Would you mind checking this occasionally over the next few days and letting me know if it ever recognizes @qleuly?

The backend was not modified in this area so the functionality should be the same (since the front end simply makes a get request for the data).

**Comment by ludochane** [comment]
In the previous version, as far as I can remember, the suggestion was instantaneous.
And no problem I will check this over the next few days.

**Comment by ludochane** [comment]
Okay, today @qleuly is suggested to me. Maybe it was yesterday I did not check.
