### ISSUE TITLE
Google Auth not persisted

### ISSUE THREAD

**Issue by tchassagnette** [ippontech/tatami#904]
Google authentication works fine but when I leave Tatami and come back in a different tab I have to re authenticate.

FYI I have two Google accounts configured on my Chrome browser (Ippon and personal)

**Comment by JustinRisch** [comment]
I have 2 accounts as well, and it seems to be working fine for me. Even after having closed chrome entirely, and then going to "http://www.app.tatamisoft.com/#/home/timeline", it will remember me. 

Can you tell me more about how I could replicate this bug?

**Comment by tchassagnette** [comment]
I'm not able to reproduce it on Chrome on my Mac at home but on Safari I have the same behaviour.
I've shared with you a small video on your Ippon account

**Comment by tchassagnette** [comment]
OK I tried something else with Safari.
If I go to app.tatamisoft.com login page is always displayed to me but if I go to http://www.app.tatamisoft.com/#/home/timeline it works just fine.

On Chrome both URL send me to the timeline as expected.

**Comment by JustinRisch** [comment]
That's very interesting, but unfortunately I have no idea on how to address that. The login page *should* redirect you if you're logged in, but it sounds like browsers don't always like checking for the user when you first navigate to the site. 

Hmmm... I would recommend, for now, bookmarking the "home" page rather than the login one. That one *will* navigate you out if you are not logged in.
