### ISSUE TITLE
Email notifications seem to be broken

### ISSUE THREAD

**Issue by aseigneurin** [ippontech/tatami#906]
I got mentioned by another user (http://www.app.tatamisoft.com/#/home/status/9cb41510-fa76-11e4-9e5a-fe54008898dc) but never received an email.

Are email notifications broken?

**Comment by JustinRisch** [comment]
It would seem that the application is having difficulty communicating with both the LDAP and Email server. We think that this may be from a variance in our deployment method though, since the code works on localhost, and has not changed since the last release (regarding those two parts of the code).

**Comment by aseigneurin** [comment]
Seems to be fixed now. Closing.
