### ISSUE TITLE
The build is broken

### ISSUE THREAD

**Issue by jdubois** [ippontech/tatami#908]
I realize I'm the only one to get notified by a broken build:
https://drone.io/github.com/ippontech/tatami

And this has been broken for a long time! Can you give me a mailing list which will be notified upon project build?
And can you check what's failing, of course? :-D

**Comment by JustinRisch** [comment]
We've actually switched to Jenkins for this, locally hosted! @bescott1 may be able to confirm this, but I feel like having both would be redundant. 

As for why that's broken : We've changed a lot of dependencies and our overall file structure since the Drone appears to have been made. It would not surprise me if it has false-positives. However, running the "mvn test" command locally shows no failures in the current build, and Jenkins reports no failures either.

**Comment by jdubois** [comment]
OK!
Then can you remove the "build" logo on the main page?
