### ISSUE TITLE
"Remember me" does not seem to work

### ISSUE THREAD

**Issue by aseigneurin** [ippontech/tatami#920]
I logged in using LDAP auth and checked the "Remember me" box. However, after a an hour or two, I got logged out with message "User logged out due to inactivity."

I should stay logged in for a longer period of time (one month?).

**Comment by JustinRisch** [comment]
That is working as intended actually! If you leave your window open for longer than half an hour without clicking, scrolling, or navigating the page, you will be logged out to prevent other people from being able to post as you. Suppose, for example, you were to accidentally leave it logged in at a library! Since Tatami is designed for company use, you could risk leaking company information or allowing someone to act very unprofessionally while pretending to be you). If you close the window and open it when you want to post something later, or simply click periodically, it should remember you correctly.

**Comment by aseigneurin** [comment]
I understand your concern but this is going to be very frustrating to have that popup each time I go back to Tatami (let's say once an hour).

Gmail is also a corporate tool and you don't get logged out so often. I find Tatami should behave the same way.

**Comment by aseigneurin** [comment]
Another issue is, when the log out triggers, the popup gets the focus (at least on Chrome). Then, you have to switch back to the tab you were working on.

**Comment by JustinRisch** [comment]
I agree with the latter issue. Is there a less intrusive popup than alert()? 

Part of the reason it was short was because google auth sessions are also short, so users would come back to Tatami, try to post, and end up getting the "session expired" *after* they hit post, losing what they typed in the process. This is more preemptive, albeit more invasive.

**Comment by dmartinpro** [comment]
Is there any kind of renew ticket available with Google Auth?
Regarding LDAP, since Tatami is polling the backend to see if new messages are available, how is it possible to have a session timeout? it shouldn't occur, right? (and it wasn't in some older versions).

I understand the security concern here, but the user experience is worse with such a short session.

**Comment by hcapitaine** [comment]
Justin, you were right if the app would display messages publicly but tatami is almost always private and if someone steel my account to post messages I delete them and change my password. 

+1 with David about UX

**Comment by fprot** [comment]
I agree with Alexis. My use case is mainly to leave the Tatami tab open all day in my browser and to interact with it occasionally. I think this is quite common among tatami users, so this newly implemented time-out rule is very unpractical...

Moreover, if security is a concern with my tatami usage, I will simply not check "Remember me" (as a side note "Se souvenir de moi" and not "Souviens-moi" in french...)

**Comment by rcadel** [comment]
+1 with David and François this feature is very frustrating

**Comment by stephlag** [comment]
+1 too.
I used to follow the favicon indicating how many unread messages I had but with this logout I do not see it anymore...

**Comment by jxerome** [comment]
Definitively that'a a killer app function.
I mean the kind of function that can kill the app because it's so annoying.

**Comment by JustinRisch** [comment]
We will correct this soon. We realize it may have been frustrating, for which we apologize, but it was necessary to prevent another issue that was raised-- the user was not being informed when session timed out, and was able to "post" still. The post would not go through, and they would see a 500 error, losing whatever they typed and forcing them to log in again. 

Anyways, we're taking another method. Rather than timing out after 30 minutes, we will instead poll the server periodically. If the session has already timed out, then we will redirect to login page with a message. This should lengthen the amount of time before a log out happens quite considerably.

**Comment by JustinRisch** [comment]
Solution deployed.
