### ISSUE TITLE
Can't follow people any more

### ISSUE THREAD

**Issue by mleneveut** [ippontech/tatami#942]
The buttons "+" in the "Who to follow" portlet doesn't work anymore, as the "Follow" button in the person profil.

Problem with Chrome 49 and Firefox 45.

**Comment by hegek87** [comment]
I'm unable to recreate this. Using the production instance (tatami.ippon.fr), this works for me with both Chrome 49, and Firefox 45.

Would you mind providing me with some more information? What exactly happens when you click the follow button? Are you using the production instance, or a local instance (or something else)?

I tested as follows:

From the timeline, in the "Who to follow" portlet, I followed a user. 

In the network traffic, the request returns 200, the user is now a friend, and the "+" becomes a blue "-". 

I verify that I'm following this user in two ways:

1. Visting the users profile, I see the following image 
<img width="255" alt="screen shot 2016-03-30 at 9 31 45 am" src="https://cloud.githubusercontent.com/assets/1440543/14143632/5d7d5d3a-f65a-11e5-8ddd-ec61d1f16d2a.png">

2. Visiting Account -> users, I see the user in my list of followed users.

Similarly, I repeated the above from the users profile page and everything works as expected. Repeating the two processes above to unfollow a user also results in me no longer following the user.

**Comment by mleneveut** [comment]
For me nothing happens, the button doesn't transform into a "-" or "Following".

But I looked at the Network tab in my browser console, and I think it is because of the PATCH request : 
PATCH http://app.tatamisoft.com/tatami/rest/users/glavigne net::ERR_EMPTY_RESPONSE

It could be blocked by the proxy of my client.
If it is working for you, nevermind, we can close this ticket.
